export const ENTITY_CHANGE_DISPLAY_NAME_EVENT = '@@entity/ENTITY_CHANGE_DISPLAY_NAME_EVENT';
export const ENTITY_DELETE_COMPONENT_EVENT = '@@entity/ENTITY_DELETE_COMPONENT_EVENT';
export const ENTITY_SET_COMPONENT_EVENT = '@@entity/ENTITY_SET_COMPONENT_EVENT';

export const NODE_LIST_DELETE_NODE_EVENT = '@@nodeList/NODE_LIST_DELETE_NODE_EVENT';
export const NODE_LIST_SET_NODE_EVENT = '@@nodeList/NODE_LIST_SET_NODE_EVENT';
